export const ROUTES = {
  MAIN_DRAWER: 'MainDrawer',
  SYSTEM_MODAL: 'SystemModal',
  HOME: 'Home',
  PROFILE: 'Profile',
  MESSAGES: 'Messages',
  ADMIN_DASHBOARD: 'AdminDashboard',
  LOGIN: 'Login',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  REGISTER: 'Register',
  FAVOURITES: 'Favourites',
  CART: 'Cart',
  PACKAGES: 'Marketplace',
  PRODUCT_DETAILS: 'ProductDetails',
  PACKAGE_DETAILS: 'PackageDetails',
} as const;
